name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Deno
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # For Deno Deploy auth
      contents: read   # To checkout repo contents

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔨 Build Project
        run: npm run build

      - name: 🚀 Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: "out-of-scope" # update to your actual project name on Deno Deploy
          entrypoint: "main.ts"   # should be a proper Deno script, not file_server.ts
          root: "dist"
